#!/bin/sh

echo "Running pre-commit hook..."

repo_root=$(git rev-parse --show-toplevel)

md_files=$(git diff --cached --name-only | grep '\.md$')

if [ -z "$md_files" ]; then
    echo "No .md files detected, skipping update-readme script"
else
    echo ".md files detected:"
    echo "$md_files"
    echo "Running update-readme script..."

    npx update-readme

    if [ $? -eq 0 ]; then
        echo "update-readme script executed successfully"
        readme_path=$(node -p "const config = require('${repo_root}/readmeConfig.json'); `${repo_root}/${config.readmePath || 'README.md'}`")
        echo "$repo_root Updating README.md at $readme_path"
        git add "$readme_path"

        if [ $? -eq 0 ]; then
            echo "$readme_path successfully added to the staging area"
        else
            echo "Failed to add $readme_path to the staging area"
            exit 1
        fi
    else
        echo "update-readme script failed"
        exit 1
    fi
fi
